version: "3"
services:
  keyvalproxy: 
    image: haproxy-keyval-img
    container_name: haproxy_keyval_cont
    build:
      context: .
      dockerfile: ./lb/Dockerfile.dev.lb
    ports: 
      - '8888:8888'
      - '443:443'
    networks:
      client-network:
      keyval-network:
    depends_on:
      - keyval
  keyval:
    image: keyval-img
    build:
      context: .
      dockerfile: ./keyValStore/Dockerfile
    ports:
      - '9876'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - keyval-data:/usr/src/keyval
    networks:
      keyval-network:
    healthcheck:
      test: curl --fail http://localhost:9876/poll || kill 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
networks:
  client-network:
    driver: bridge
  keyval-network:
    driver: bridge
volumes:
  keyval-data: